spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ${MAIL_PASSWORD}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
server:
  error:
    include-message: always
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger
    writer-with-default-pretty-printer: 'true'
    operationsSorter: method